package db

var username = []string{
	"Alex", "John", "Tom", "Max", "Django",
	"Emily", "Sophia", "Liam", "Olivia", "Noah",
	"Mason", "Ava", "Isabella", "Ethan", "James",
	"Charlotte", "Amelia", "Benjamin", "Lucas", "Mia",
	"Logan", "Elijah", "Harper", "Henry", "Grace",
	"Daniel", "Michael", "Ella", "Jack", "Chloe",
	"Leo", "William", "Aria", "Alexander", "Layla",
	"Nathan", "Samuel", "Luna", "Jacob", "Aiden",
	"Ella", "Scarlett", "Owen", "Hannah", "Evelyn",
	"Ryan", "Zoe", "Caleb", "Lily", "Sebastian",
	"David", "Aurora", "Mateo", "Abigail", "Julian",
}

var email = []string{
	"alex@gmail.com", "john@gmail.com", "tom@gmail.com", "max@gmail.com", "django@gmail.com",
	"emily@gmail.com", "sophia@gmail.com", "liam@gmail.com", "olivia@gmail.com", "noah@gmail.com",
	"mason@gmail.com", "ava@gmail.com", "isabella@gmail.com", "ethan@gmail.com", "james@gmail.com",
	"charlotte@gmail.com", "amelia@gmail.com", "benjamin@gmail.com", "lucas@gmail.com", "mia@gmail.com",
	"logan@gmail.com", "elijah@gmail.com", "harper@gmail.com", "henry@gmail.com", "grace@gmail.com",
	"daniel@gmail.com", "michael@gmail.com", "ella@gmail.com", "jack@gmail.com", "chloe@gmail.com",
	"leo@gmail.com", "william@gmail.com", "aria@gmail.com", "alexander@gmail.com", "layla@gmail.com",
	"nathan@gmail.com", "samuel@gmail.com", "luna@gmail.com", "jacob@gmail.com", "aiden@gmail.com",
	"ella2@gmail.com", "scarlett@gmail.com", "owen@gmail.com", "hannah@gmail.com", "evelyn@gmail.com",
	"ryan@gmail.com", "zoe@gmail.com", "caleb@gmail.com", "lily@gmail.com", "sebastian@gmail.com",
	"david@gmail.com", "aurora@gmail.com", "mateo@gmail.com", "abigail@gmail.com", "julian@gmail.com",
}

var titles = []string{
	"Exploring the Future of AI",
	"My Morning Routine for Success",
	"Why Go Is My Favorite Programming Language",
	"The Beauty of Simplicity in Design",
	"Top 5 Tips to Stay Productive",
	"How I Learned to Code in 100 Days",
	"Building a Social App from Scratch",
	"Why Consistency Beats Motivation",
	"Reflections on My First Tech Job",
	"Learning Machine Learning the Hard Way",
}
var comments = []string{
	"Awesome post! 🔥",
	"Totally agree with you.",
	"Nice work, keep it up!",
	"Wow, this is really insightful.",
	"Love this idea!",
	"Can’t wait to try this myself.",
	"Very well explained 👏",
	"Thanks for sharing!",
	"That’s exactly what I needed today.",
	"You nailed it 💯",
	"Interesting perspective!",
	"Bro, this is next level 😎",
	"Really inspiring post.",
	"Keep posting stuff like this!",
	"Great advice — simple and powerful.",
	"Love your consistency!",
	"Following your journey, man!",
	"Solid thoughts on this topic.",
	"Couldn’t agree more!",
	"Respect for the grind 💪",
	"Just what I was looking for!",
	"This made my day 🙌",
	"Your posts always hit different.",
	"Great read — thanks for sharing.",
	"I’m gonna bookmark this one!",
	"Well said 👏👏👏",
	"Definitely sharing this with friends.",
	"Short but meaningful.",
	"That’s an interesting take!",
	"You always bring good energy 🔥",
	"Loved this example!",
	"Clear and on point.",
	"I wish more people thought like this.",
	"Always learning something new from you.",
	"This deserves more attention!",
	"Legendary post 💯",
	"Simple yet so powerful.",
	"Keep inspiring others 🙏",
	"Facts only 👌",
	"Bro, this motivated me today!",
	"Perfect timing for me to read this.",
	"Can’t stop thinking about this topic now.",
	"Wow, well written and deep.",
	"Totally saving this for later.",
	"That’s pure wisdom!",
	"Man, this post speaks to me.",
	"Love your mindset.",
	"Keep doing your thing 👏",
	"Good stuff, as always.",
	"This is gold 🔥🔥🔥",
	"Motivated to grind even harder now.",
}

var contents = []string{
	"Just finished writing some exciting new code. Can't wait to share it!",
	"Go has been an absolute game-changer for backend development.",
	"Life is about creating balance between hard work and rest.",
	"Started a new project using Go and Postgres — performance is amazing!",
	"Taking small steps every day toward a big goal.",
	"Working on improving my skills in AI and data science.",
	"Consistency and discipline are key to success in programming.",
	"Debugging for hours, but that one ‘aha!’ moment makes it worth it.",
	"Coffee, code, and good vibes ☕💻",
	"Learning never stops — one commit at a time.",
}

var tagPool = [][]string{
	{"tech", "coding", "golang"},
	{"lifestyle", "motivation", "productivity"},
	{"ai", "machine-learning", "future"},
	{"design", "creativity", "inspiration"},
	{"backend", "development", "database"},
	{"self-improvement", "focus", "discipline"},
	{"career", "growth", "learning"},
	{"software", "engineering", "projects"},
	{"cloud", "microservices", "devops"},
	{"frontend", "react", "javascript"},
}
